# Generated by Django 6.0.2 on 2026-04-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending Review', 'pending review'), ('Order Confirmed', 'order confirmed'), ('Received From Seller', 'received from seller'), ('Preparing Order', 'preparing order'), ('Deliverd Due To Postal Service', 'deliverd to postal service'), ('Refunded Due To Out Of Stock', 'refunded due to out of stock')], default='Pending Review'),
        ),
    ]
