# Generated by Django 6.0.2 on 2026-04-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PR', 'pending review'), ('oc', 'order confirmed'), ('RFS', 'received from seller'), ('PO', 'preparing order'), ('DTPS', 'deliverd to postal service'), ('RDTOOS', 'refunded due to out of stock')], default='PR'),
        ),
    ]
