# Generated by Django 6.0.2 on 2026-02-24 11:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='date_join',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
