# Generated by Django 6.0.2 on 2026-05-01 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('failed', 'failed')], default='pending'),
        ),
    ]
