# Generated by Django 6.0.2 on 2026-02-11 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام کتگوری')),
                ('slug', models.SlugField(max_length=255)),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': ' دسته بندی ها',
                'ordering': ['-name'],
                'indexes': [models.Index(fields=['name'], name='shop_catego_name_289c7e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('slug', models.SlugField(max_length=255, verbose_name='اسلاگ')),
                ('description', models.TextField(max_length=1200, verbose_name='توضیحات')),
                ('inventory', models.PositiveIntegerField(verbose_name='موجودی')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت')),
                ('off', models.PositiveIntegerField(default=0, verbose_name='تخفیف')),
                ('new_price', models.PositiveIntegerField(default=0, verbose_name='قیمت ئس از تخفیف')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایحاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': ' محصولات',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name='موضوع')),
                ('image_field', models.ImageField(upload_to='image_of_product/')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ساخت')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'عکس',
                'verbose_name_plural': 'عکس ها',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Productfeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('value', models.CharField(max_length=255, verbose_name='مثدار ویژگی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature', to='shop.product', verbose_name='ویژگی ها')),
            ],
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['id', 'slug'], name='shop_produc_id_f21274_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='shop_produc_name_a2070e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created'], name='shop_produc_created_ef211c_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['-created'], name='shop_image_created_9f3f47_idx'),
        ),
    ]
